
export const pimlocators = {
    pimmenu: ".oxd-main-menu-item",
    addempTab: ".oxd-topbar-body-nav-tab",
    EmpFirstName: "//input[@placeholder='First Name']",
    EmpMidName: "//input[@placeholder='Middle Name']",
    EmpLastName: "//input[@placeholder='Last Name']",
    EmpID: "(//input[@class='oxd-input oxd-input--active'])[2]",
    EditGender: "input[type=radio]:nth-child(1):nth-child(1)",
    EmpbuttonSave: "//button[@type='submit']",
    EmpInfoSave: "(//button[@type='submit'][normalize-space()='Save'])[1]",
    listEmpNavTab: ".oxd-topbar-body-nav-tab",
    listEmployeeName: ".oxd-autocomplete-text-input",
    listEmployeeNameSelect: ".oxd-autocomplete-dropdown",
    listEmpSearchbtn: "//button[normalize-space()='Search']",
    editEmplistbtn: "//div[@class='orangehrm-container']//button[1]",
    successfullyMsg: "//div[@id='oxd-toaster_1']",
    deleteButton: ".oxd-icon-button.oxd-table-cell-action-space",
    deleteDialogBox: "div[role='document']",
    deleteYesButton: "//button[normalize-space()='Yes, Delete']",
    deleteNoButton: "//button[normalize-space()='No, Cancel']",
    deleteMsg: "//div[@id='oxd-toaster_1']",
    nationalityDropdown: ".oxd-select-text-input",
    maritalDropdown: ".oxd-select-text-input"
}